In [7]:
import torch

a=torch.rand((2,2))
b=torch.rand((2,2))
a


tensor([[0.5107, 0.4258],
        [0.5085, 0.1778]])

In [8]:
b

tensor([[0.7410, 0.7256],
        [0.0662, 0.7665]])

In [9]:
torch.matmul(a,b)

tensor([[0.4066, 0.6970],
        [0.3886, 0.5053]])

In [10]:
import numpy as np

a=np.random.rand(2,2)
b=np.random.rand(2,2)

np.dot(a,b)

array([[0.4104892 , 0.29291389],
       [1.17965593, 0.82764002]])

In [13]:
#pytorch ta
a=torch.rand((2,2))
b=torch.rand((2,2))
a*b

tensor([[0.3714, 0.2837],
        [0.4193, 0.3680]])

In [15]:
#numpy da
a=np.random.rand(2,2)
b=np.random.rand(2,2)

np.multiply(a,b)

array([[0.10642522, 0.20140924],
       [0.09378891, 0.49622308]])

# ZERO AND ONES MATRİX

In [17]:
a_torch=torch.zeros(2,2)
a_torch

tensor([[0., 0.],
        [0., 0.]])

In [19]:
a_numpy=np.zeros((2,2))
a_numpy

array([[0., 0.],
       [0., 0.]])

In [20]:
b_torch=torch.ones(2,2)
b_torch

tensor([[1., 1.],
        [1., 1.]])

In [21]:
b_numpy=np.ones((2,2))
b_numpy

array([[1., 1.],
       [1., 1.]])

In [22]:
#birim matris
c_torch=torch.eye(2)
c_torch

tensor([[1., 0.],
        [0., 1.]])

In [23]:
c_numpy=np.identity(2)
c_numpy

array([[1., 0.],
       [0., 1.]])